# Generated by Django 3.0.3 on 2020-02-10 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_todos',
        ),
    ]
