# Generated by Django 3.0.3 on 2020-02-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_post_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pre_moderation',
            field=models.BooleanField(default=False),
        ),
    ]
